
spring:
    application:
        name: ${PRODUCER_APPLICATION_NAME:EDMIDC-Producer-Service}
    kafka:
        consumer:
            auto-offset-reset: earliest
            bootstrap-servers: ${KAFKA_BOOTSTRAP_URL:localhost:29092}
            group-id: ${GROUP_ID:group_id}
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            acks: -1
            bootstrap-servers: ${KAFKA_BOOTSTRAP_URL:localhost:29092}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        topic: ${TOPIC_NAME:edmidc-bitcoin-cdc}
        errorTopic: ${ERROR_TOPIC:error-message-cdc}
    resource:
        url: ${RESOURCE_URL:https://api.coinlore.net/api/ticker/?id=90}
        measurementName: ${RESOURCE_MEASUREMENT_NAME:Subject}
        tag: ${RESOURCE_TAG:tag}
        frequency: ${RESOURCE_FREQUENCY:0 * * * * *}

    datasource:
        url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/heartbeatDB}
        username: ${POSTGRES_USER:edmidcUser}
        password: ${POSTGRES_PASSWORD:edmidc}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
management:
    server:
        port: ${SERVER_PORT:8081}
server:
    port: ${SERVER_PORT:8081}
    servlet:
        context-path: /
